Fix flipped
mcbridejc/kicad_component_layout pull request #4
Opened 2022-06-24 05:18 UTC by l4u

* get flipped from props
* use XOR to simplify the code

2022-06-25 16:40 UTC, mcbridejc requested changes
Ugh. Thanks for catching this. I guess I didn't try to put any components on the bottom while testing with v6...

Just a couple comments below; I'm trying at least for now to maintain compatibility with v5.

2022-06-25 16:40 UTC, mcbridejc commented on component_layout_plugin.py
> +            flip = props.get('flipped', False) # Generally, flip means put on the bottom
Arguably 'flipped' is a better name for this property, but not sufficiently better to justify breaking backwards compatibility, so I don't see any reason to change this prop name...

2022-06-25 16:40 UTC, mcbridejc commented on component_layout_plugin.py
> +                mod.Flip(mod.GetPosition(), False)
```suggestion
                if v5_compat:
                    mod.Flip(mod.GetPosition())
                else:
                    mod.Flip(mod.GetPosition(), False)
```

The aFlipLeftRight argument is new in v6.

2022-06-25 16:46 UTC, mcbridejc commented on component_layout_plugin.py
> +            flip = props.get('flipped', False) # Generally, flip means put on the bottom
Oh I see I put 'flipped' in the README example, which is a mistake on my part.

2022-06-27 00:31 UTC, l4u commented
👍 for v5 compatibility

2022-07-22 20:11 UTC, merged